/**
 * 本模块定义游戏中所有的草药
 */

import { BaseItemConfig } from "./types";

/**
 * 草药类型
 */
export enum CaoyaoType {
  // 一品
  宁心草 = "宁心草",
  银月花 = "银月花",
  // 二品
  轻灵草 = "轻灵草",
  何首乌 = "何首乌",
  天元果 = "天元果",
  火精枣 = "火精枣",
  百草露 = "百草露",
  红绫草 = "红绫草",
  玄参 = "玄参",
  风灵花 = "风灵花",
  罗犀草 = "罗犀草",
  // 三品
  乌稠木 = "乌稠木",
  雪凝花 = "雪凝花",
  龙鳞果 = "龙鳞果",
  冰精芝 = "冰精芝",
  龙须藤 = "龙须藤",
  天灵果 = "天灵果",
  玉龙参 = "玉龙参",
  七星草 = "七星草",
  火灵芝 = "火灵芝",
  // 四品
  白沉脂 = "白沉脂",
  银精芝 = "银精芝",
  血莲精 = "血莲精",
  玉髓芝 = "玉髓芝",
  鬼面花 = "鬼面花",
  混元果 = "混元果",
  月灵花 = "月灵花",
  鸡冠草 = "鸡冠草",
  绝魂草 = "绝魂草",
  狼桃 = "狼桃",
  阴凝草 = "阴凝草",
  天剑竹 = "天剑竹",
  菩提花 = "菩提花",
  补天芝 = "补天芝",
  鬼臼草 = "鬼臼草",
  枫香脂 = "枫香脂",
  太清玄灵草 = "太清玄灵草",
  // 五品
  地火心芝 = "地火心芝",
  天蚕灵叶 = "天蚕灵叶",
  雪骨玉参 = "雪骨玉参",
  腐骨灵花 = "腐骨灵花",
  叁叶清芝 = "叁叶清芝",
  七彩月兰 = "七彩月兰",
  叁尾凤叶 = "叁尾凤叶",
  冰焰灵草 = "冰焰灵草",
  厉魂血魄 = "厉魂血魄",
  渊血冥花 = "渊血冥花",
  龙皇果 = "龙皇果",
  鎾金灵花 = "鎾金灵花",
  森檀木 = "森檀木",
  浩渺水藤 = "浩渺水藤",
  焰芒果 = "焰芒果",
  无垠灵参 = "无垠灵参",
  道运花 = "道运花",
  问道花 = "问道花",
  太玄问心果 = "太玄问心果",
  炼髓藤 = "炼髓藤",
  重元换血草 = "重元换血草",
  壁莹花 = "壁莹花",
  黄泉花 = "黄泉花",
  天问花 = "天问花",
  青灵芝 = "青灵芝",
}

/**
 * 草药的配置
 */
export interface CaoYaoConfig extends BaseItemConfig {
  type: "草药";
  /** 品级 */
  grade: number;
}

/**
 * 所有草药的配置
 */
export const CAOYAO_CONFIGS: Record<CaoyaoType, CaoYaoConfig> = {
  // 一品
  宁心草: {
    type: "草药",
    id: CaoyaoType.宁心草,
    name: "宁心草",
    description:
      "一种常见的仙草，常用于炼制清心静气用的丹药。但过量使用或会导致发呆，反应迟钝，短时间内修为停滞等情况。",
    grade: 1,
  },
  银月花: {
    type: "草药",
    id: CaoyaoType.银月花,
    name: "银月花",
    description: "在月光下会泛出银色光芒的花朵，常用于炼制提升感知能力的丹药。",
    grade: 1,
  },
  // 二品
  轻灵草: {
    type: "草药",
    id: CaoyaoType.轻灵草,
    name: "轻灵草",
    description: "叶片轻盈，随风飘动的灵草，能够提升身法速度。",
    grade: 2,
  },
  何首乌: {
    type: "草药",
    id: CaoyaoType.何首乌,
    name: "何首乌",
    description: "具有滋补功效的药材，能够增强气血和生命力。",
    grade: 2,
  },
  天元果: {
    type: "草药",
    id: CaoyaoType.天元果,
    name: "天元果",
    description: "蕴含天地元气的果实，是炼制筑基丹的重要材料。",
    grade: 2,
  },
  火精枣: {
    type: "草药",
    id: CaoyaoType.火精枣,
    name: "火精枣",
    description: "蕴含火属性精华的枣子，能够增强火系法术的威力。",
    grade: 2,
  },
  百草露: {
    type: "草药",
    id: CaoyaoType.百草露,
    name: "百草露",
    description: "采集百草精华凝结而成的露水，具有解毒功效。",
    grade: 2,
  },
  红绫草: {
    type: "草药",
    id: CaoyaoType.红绫草,
    name: "红绫草",
    description: "叶片如红绫般柔软的灵草，能够活血化瘀，治疗内伤。",
    grade: 2,
  },
  玄参: {
    type: "草药",
    id: CaoyaoType.玄参,
    name: "玄参",
    description: "根部呈玄黑色的参类，能够滋阴降火，平衡体内阴阳。",
    grade: 2,
  },
  风灵花: {
    type: "草药",
    id: CaoyaoType.风灵花,
    name: "风灵花",
    description: "蕴含风之灵力的花朵，能够提升移动速度和闪避能力。",
    grade: 2,
  },
  罗犀草: {
    type: "草药",
    id: CaoyaoType.罗犀草,
    name: "罗犀草",
    description: "叶片坚硬如犀角的灵草，能够增强防御力。",
    grade: 2,
  },
  // 三品
  乌稠木: {
    type: "草药",
    id: CaoyaoType.乌稠木,
    name: "乌稠木",
    description: "木质乌黑稠密的灵木，能够稳定心神，防止走火入魔。",
    grade: 3,
  },
  雪凝花: {
    type: "草药",
    id: CaoyaoType.雪凝花,
    name: "雪凝花",
    description: "生长在雪山之巅的花朵，蕴含冰寒之力，能够炼制冰系丹药。",
    grade: 3,
  },
  龙鳞果: {
    type: "草药",
    id: CaoyaoType.龙鳞果,
    name: "龙鳞果",
    description: "表皮如龙鳞般的奇异果实，能够增强体魄和力量。",
    grade: 3,
  },
  冰精芝: {
    type: "草药",
    id: CaoyaoType.冰精芝,
    name: "冰精芝",
    description: "蕴含纯净冰精的灵芝，能够抵御心魔，保持灵台清明。",
    grade: 3,
  },
  龙须藤: {
    type: "草药",
    id: CaoyaoType.龙须藤,
    name: "龙须藤",
    description: "藤蔓如龙须般纤细而坚韧，能够增强经脉强度。",
    grade: 3,
  },
  天灵果: {
    type: "草药",
    id: CaoyaoType.天灵果,
    name: "天灵果",
    description: "吸收天地灵气的果实，能够快速恢复消耗的法力。",
    grade: 3,
  },
  玉龙参: {
    type: "草药",
    id: CaoyaoType.玉龙参,
    name: "玉龙参",
    description: "形如玉龙的珍稀参类，能够大幅提升修为和寿命。",
    grade: 3,
  },
  七星草: {
    type: "草药",
    id: CaoyaoType.七星草,
    name: "七星草",
    description: "叶子上有七个星状斑点的灵草，能够增强星辰之力的感应。",
    grade: 3,
  },
  火灵芝: {
    type: "草药",
    id: CaoyaoType.火灵芝,
    name: "火灵芝",
    description: "蕴含强大火灵力的灵芝，能够提升火系灵根的品质。",
    grade: 3,
  },
  // 四品
  白沉脂: {
    type: "草药",
    id: CaoyaoType.白沉脂,
    name: "白沉脂",
    description: "白色沉重的脂状物，能够稳固根基，防止修为倒退。",
    grade: 4,
  },
  银精芝: {
    type: "草药",
    id: CaoyaoType.银精芝,
    name: "银精芝",
    description: "表面泛着银光的灵芝，能够提升金属性法术的威力。",
    grade: 4,
  },
  血莲精: {
    type: "草药",
    id: CaoyaoType.血莲精,
    name: "血莲精",
    description: "血色莲花的花蕊精华，能够激发潜能，临时提升实力。",
    grade: 4,
  },
  玉髓芝: {
    type: "草药",
    id: CaoyaoType.玉髓芝,
    name: "玉髓芝",
    description: "质地如玉髓般的灵芝，能够净化法力，提升法力纯度。",
    grade: 4,
  },
  鬼面花: {
    type: "草药",
    id: CaoyaoType.鬼面花,
    name: "鬼面花",
    description: "花朵形似鬼脸，能够炼制迷惑心智或增强神识的丹药。",
    grade: 4,
  },
  混元果: {
    type: "草药",
    id: CaoyaoType.混元果,
    name: "混元果",
    description: "蕴含混沌元气的果实，能够平衡体内各种属性的灵力。",
    grade: 4,
  },
  月灵花: {
    type: "草药",
    id: CaoyaoType.月灵花,
    name: "月灵花",
    description: "吸收月华之力的花朵，能够提升阴属性功法的修炼速度。",
    grade: 4,
  },
  鸡冠草: {
    type: "草药",
    id: CaoyaoType.鸡冠草,
    name: "鸡冠草",
    description: "形似鸡冠的红色灵草，能够增强气血，提升体力恢复速度。",
    grade: 4,
  },
  绝魂草: {
    type: "草药",
    id: CaoyaoType.绝魂草,
    name: "绝魂草",
    description: "带有剧毒的灵草，能够炼制毒丹或用于以毒攻毒的疗法。",
    grade: 4,
  },
  狼桃: {
    type: "草药",
    id: CaoyaoType.狼桃,
    name: "狼桃",
    description: "外形似狼头的桃子，能够增强嗅觉和感知能力。",
    grade: 4,
  },
  阴凝草: {
    type: "草药",
    id: CaoyaoType.阴凝草,
    name: "阴凝草",
    description: "生长在极阴之地的灵草，能够炼制阴属性丹药。",
    grade: 4,
  },
  天剑竹: {
    type: "草药",
    id: CaoyaoType.天剑竹,
    name: "天剑竹",
    description: "竹身笔直如剑，叶片锋利，能够增强剑道感悟。",
    grade: 4,
  },
  菩提花: {
    type: "草药",
    id: CaoyaoType.菩提花,
    name: "菩提花",
    description: "传说中菩提树开出的花朵，能够提升悟性和智慧。",
    grade: 4,
  },
  补天芝: {
    type: "草药",
    id: CaoyaoType.补天芝,
    name: "补天芝",
    description: "传说中女娲补天时散落的灵气所化，能够修复根基损伤。",
    grade: 4,
  },
  鬼臼草: {
    type: "草药",
    id: CaoyaoType.鬼臼草,
    name: "鬼臼草",
    description: "生长在幽冥之地的灵草，能够炼制与魂魄相关的丹药。",
    grade: 4,
  },
  枫香脂: {
    type: "草药",
    id: CaoyaoType.枫香脂,
    name: "枫香脂",
    description: "枫树分泌的特殊树脂，能够安神定魂，防止外邪入侵。",
    grade: 4,
  },
  太清玄灵草: {
    type: "草药",
    id: CaoyaoType.太清玄灵草,
    name: "太清玄灵草",
    description: "蕴含太清玄气的灵草，能够提升道法修炼速度。",
    grade: 4,
  },
  // 五品
  地火心芝: {
    type: "草药",
    id: CaoyaoType.地火心芝,
    name: "地火心芝",
    description: "生长在地心火脉中的灵芝，蕴含强大的火灵之力。",
    grade: 5,
  },
  天蚕灵叶: {
    type: "草药",
    id: CaoyaoType.天蚕灵叶,
    name: "天蚕灵叶",
    description: "天蚕食用的灵叶，能够增强丝状法宝的韧性和强度。",
    grade: 5,
  },
  雪骨玉参: {
    type: "草药",
    id: CaoyaoType.雪骨玉参,
    name: "雪骨玉参",
    description: "通体如雪如玉的参类，能够重塑筋骨，提升修炼资质。",
    grade: 5,
  },
  腐骨灵花: {
    type: "草药",
    id: CaoyaoType.腐骨灵花,
    name: "腐骨灵花",
    description: "生长在腐骨之上的诡异花朵，能够炼制剧毒或特殊丹药。",
    grade: 5,
  },
  叁叶清芝: {
    type: "草药",
    id: CaoyaoType.叁叶清芝,
    name: "叁叶清芝",
    description: "三片叶子的清心灵芝，能够清除心魔，稳固道心。",
    grade: 5,
  },
  七彩月兰: {
    type: "草药",
    id: CaoyaoType.七彩月兰,
    name: "七彩月兰",
    description: "在月光下会呈现七种颜色的兰花，能够提升多种属性的灵力。",
    grade: 5,
  },
  叁尾凤叶: {
    type: "草药",
    id: CaoyaoType.叁尾凤叶,
    name: "叁尾凤叶",
    description: "形似凤凰尾羽的三片叶子，能够提升飞行速度和风系法术威力。",
    grade: 5,
  },
  冰焰灵草: {
    type: "草药",
    id: CaoyaoType.冰焰灵草,
    name: "冰焰灵草",
    description: "同时蕴含冰与火之力的奇异灵草，能够平衡冰火属性冲突。",
    grade: 5,
  },
  厉魂血魄: {
    type: "草药",
    id: CaoyaoType.厉魂血魄,
    name: "厉魂血魄",
    description: "由厉魂和血魄凝聚而成的特殊材料，能够炼制增强神魂的丹药。",
    grade: 5,
  },
  渊血冥花: {
    type: "草药",
    id: CaoyaoType.渊血冥花,
    name: "渊血冥花",
    description: "生长在幽冥血海的花朵，能够炼制与血道相关的丹药。",
    grade: 5,
  },
  龙皇果: {
    type: "草药",
    id: CaoyaoType.龙皇果,
    name: "龙皇果",
    description: "传说中龙皇精血所化的果实，能够大幅提升体魄和龙族血脉。",
    grade: 5,
  },
  鎾金灵花: {
    type: "草药",
    id: CaoyaoType.鎾金灵花,
    name: "鎾金灵花",
    description: "花瓣如鎾金般闪耀的花朵，能够提升金属性灵根的品质。",
    grade: 5,
  },
  森檀木: {
    type: "草药",
    id: CaoyaoType.森檀木,
    name: "森檀木",
    description: "古老森林中的檀香木，能够宁心安神，提升木系法术威力。",
    grade: 5,
  },
  浩渺水藤: {
    type: "草药",
    id: CaoyaoType.浩渺水藤,
    name: "浩渺水藤",
    description: "生长在浩瀚水域中的藤蔓，能够提升水属性灵力的掌控力。",
    grade: 5,
  },
  焰芒果: {
    type: "草药",
    id: CaoyaoType.焰芒果,
    name: "焰芒果",
    description: "蕴含火焰之力的芒果，能够增强火系法术的爆发力。",
    grade: 5,
  },
  无垠灵参: {
    type: "草药",
    id: CaoyaoType.无垠灵参,
    name: "无垠灵参",
    description: "传说中生长在无垠虚空中的参类，能够扩展丹田容量。",
    grade: 5,
  },
  道运花: {
    type: "草药",
    id: CaoyaoType.道运花,
    name: "道运花",
    description: "蕴含道运之力的花朵，能够提升修士的气运和机缘。",
    grade: 5,
  },
  问道花: {
    type: "草药",
    id: CaoyaoType.问道花,
    name: "问道花",
    description: "能够帮助修士感悟天道的奇异花朵，提升突破境界的几率。",
    grade: 5,
  },
  太玄问心果: {
    type: "草药",
    id: CaoyaoType.太玄问心果,
    name: "太玄问心果",
    description: "太玄秘境中生长的问心果，能够帮助修士明心见性，坚定道心。",
    grade: 5,
  },
  炼髓藤: {
    type: "草药",
    id: CaoyaoType.炼髓藤,
    name: "炼髓藤",
    description: "能够淬炼骨髓，提升根骨的奇异藤蔓。",
    grade: 5,
  },
  重元换血草: {
    type: "草药",
    id: CaoyaoType.重元换血草,
    name: "重元换血草",
    description: "能够重塑血液，提升血脉品质的珍稀灵草。",
    grade: 5,
  },
  壁莹花: {
    type: "草药",
    id: CaoyaoType.壁莹花,
    name: "壁莹花",
    description: "生长在悬崖壁上的莹光花朵，能够提升视力与洞察力。",
    grade: 5,
  },
  黄泉花: {
    type: "草药",
    id: CaoyaoType.黄泉花,
    name: "黄泉花",
    description: "生长在黄泉路边的诡异花朵，能够炼制与生死相关的丹药。",
    grade: 5,
  },
  天问花: {
    type: "草药",
    id: CaoyaoType.天问花,
    name: "天问花",
    description: "传说中能够沟通天地的花朵，提升对天道法则的感悟。",
    grade: 5,
  },
  青灵芝: {
    type: "草药",
    id: CaoyaoType.青灵芝,
    name: "青灵芝",
    description: "蕴含生命精华的青色灵芝，能够延年益寿，恢复生机。",
    grade: 5,
  },
};

/**
 * 不同品级草药的采集时间，单位天
 */
export const CAOYAO_GATHER_TIME: Record<number, number> = {
  1: 1,
  2: 2,
  3: 4,
  4: 8,
  5: 16,
  6: 32,
};
